### ISSUE TITLE
Use of grouping "ao" elsewhere

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#70]
A future update of RFC8177 or an extension may have to use "grouping ao" to store SendID and RecvID in the key-chain. 

For instance, draft-ietf-opsawg-l3sm-l3nm assumes such an extension of RFC8177.

Actual examples include:

https://www.juniper.net/documentation/en_US/junos/topics/reference/general/release-notes/20.3/infocus-topicmaps/tcp-authentication-option-map-infocus.html 

https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5500/bgp/72x/b-bgp-cg-ncs5500-72x/implementing-master-key-tuple-configuration.html#id_77361 

https://datatracker.ietf.org/meeting/112/materials/slides-112-tcpm-tcp-ao-interop-and-some-exciting-news-02.pdf

In order to be future-proof, the TCP-AO parameters defined by TCPM should be able to be re-used as generically as possible outside the module. The definition of the grouping neets to be cross-checked again.

**Comment by michael-scharf** [comment]
Mahesh, can you please verify that the grouping ao can indeed be reused easily outside this YANG module, e.g., in a key-chain?

**Comment by mjethanandani** [comment]
@michael-scharf, I went through 'grouping ao' definition, and its use in our and other drafts. I see no reason that the current definition will not work. In fact, models such as draft-ietf-opsawg-l3sm-l3nm can use the grouping even though RFC8177 do not include it, by including it directly from our draft/model. All they need to do is:

Import our module as follows:

```
import ietf-tcp {
  prefix tcp;
  reference
    "I-D.ietf-tcpm-yang-tcp: YANG model for TCP."
}
```

and in their model have this instead of (re)defining the AO parameters.

```
choice option {
  description
    "Choice of authentication options.";
  case ao {
    description
      "Uses TCP-Authentication Option (TCP-AO).";
    reference
       "RFC 5925: The TCP Authentication Option.";
    container tcp-ao {
      uses tcp:ao;
      leaf ao-keychain {
         type key-chain:key-chain-ref;
         description
             "Reference to the TCP-AO key chain.";
         reference
            "RFC 8177: YANG Key Chain.";
    }
  }
  ... rest of the model
}
```

My read of draft-ietf-opsawg-l3sm-l3nm draft is that it is not advocating that TCP-AO parameters be made part of the keychain model, (which is a generic keychain model,) but that there should be a way to include parameters such as recv-id and send-id by models that want to support TCP-AO. In fact, keychain model should not include the TCP-AO parameters, as then you assume that the transport is always TCP.

**Comment by michael-scharf** [comment]
OK, then I'll close this issue.
