### ISSUE TITLE
Review reference style

### ISSUE THREAD

**Issue by michael-scharf** [mjethanandani/ietf-tcp#71]
Many references to an RFC use the title of the RFC in the text. At least in some cases the result is difficult to parse.

While this will be fixed by the RFC editor in any case, we should probably improve at least those cases in which the title does not work well. Mohamed Boucadair has flagged some of these cases.

**Comment by mjethanandani** [comment]
I looked at Mohamed's comments, and I disagree that "RFC CCCC: <Title of the draft> is easier to read/parse compared to existing method that IETF uses to reference documents that are still in draft state, such as "I-D.ietf-netconf-tcp-client-server: <Title of the draft>

As you mention, this will ultimately be fixed by the RFC editor, and I think we can largely let them take care of it.
